"""Board lifecycle automation.

Manages the powered-dev task board:
  - Generates in-flight.md from active plans
  - Lints backlog for duplicate entries
  - Checks merge/PR gates (blocks if branch has active plan)
  - Starts and finishes tasks (scaffold stubs, move backlog entries)

Usage:
    python board.py regenerate
    python board.py lint-backlog
    python board.py start "Task title" [--tier lite|full]
    python board.py finish
    python board.py abandon
    python board.py check-merge <branch>
    python board.py check-pr <branch>
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import docs_index
from frontmatter import parse_frontmatter

# ---------------------------------------------------------------------------
# Path constants
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_ROOT = REPO_ROOT / "docs" / "superpowers"
BOARD_ROOT = REPO_ROOT / "docs" / "board"
PLANS_ROOT = DOCS_ROOT / "plans"
SPECS_ROOT = DOCS_ROOT / "specs"
BACKLOG_PATH = BOARD_ROOT / "backlog.md"
IN_FLIGHT_PATH = BOARD_ROOT / "in-flight.md"
INDEX_PATH = DOCS_ROOT / "INDEX.md"

AUTO_HEADER = "<!-- AUTO-GENERATED by scripts/board.py — DO NOT EDIT -->\n\n# In-flight\n"

# ---------------------------------------------------------------------------
# Plan stub templates
# ---------------------------------------------------------------------------

_PLAN_STUB_FULL = """---
status: active
type: plan
date: {date}
summary: {title}
branch: {branch}
tier: full
related:
  spec: {spec_filename}
---

# {title}
"""

_PLAN_STUB_LITE = """---
status: active
type: plan
date: {date}
summary: {title}
branch: {branch}
tier: lite
---

# {title}
"""

_SPEC_STUB = """---
status: active
type: spec
date: {date}
summary: {title}
---

# {title}
"""


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def _today() -> str:
    """Return today's UTC date as YYYY-MM-DD."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _current_branch() -> str:
    """Return the current git branch name."""
    result = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _slugify(title: str) -> str:
    """Convert title to lowercase-hyphenated slug."""
    slug = title.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug


def _git_add(paths: list[Path]) -> None:
    """Stage the given file paths silently."""
    str_paths = [str(p) for p in paths]
    subprocess.run(["git", "add"] + str_paths, capture_output=True, check=False)


# ---------------------------------------------------------------------------
# Core: collect and format plans
# ---------------------------------------------------------------------------

def _collect_plans(plans_root: Path) -> list[tuple[Path, dict[str, Any]]]:
    """Return list of (path, frontmatter_dict) for all plans with frontmatter."""
    results: list[tuple[Path, dict[str, Any]]] = []
    if not plans_root.is_dir():
        return results
    for p in sorted(plans_root.glob("*.md")):
        fm = parse_frontmatter(p)
        if fm is not None:
            results.append((p, fm))
    return results


def _fmt_inflight_entry(path: Path, fm: dict[str, Any]) -> str:
    """Format one in-flight entry with summary, tier, branch, plan link, optional spec link."""
    summary = fm.get("summary", path.stem)
    tier = fm.get("tier", "")
    branch = fm.get("branch", "")
    plan_link = f"[plan](plans/{path.name})"

    parts = [f"**{summary}**"]
    if tier:
        parts.append(f"`{tier}`")
    if branch:
        parts.append(f"`{branch}`")
    parts.append(plan_link)

    # Add spec link if present
    related = fm.get("related")
    if isinstance(related, dict) and "spec" in related:
        spec_name = related["spec"]
        parts.append(f"[spec](specs/{spec_name})")

    return "- " + " — ".join(parts)


# ---------------------------------------------------------------------------
# Public API: build_in_flight
# ---------------------------------------------------------------------------

def build_in_flight(plans_root: Path) -> str:
    """Render full in-flight.md content from active plans, sorted by date desc."""
    all_plans = _collect_plans(plans_root)
    active = [(p, fm) for p, fm in all_plans if fm.get("status") == "active"]

    # Sort by date descending (filename-based, YYYY-MM-DD prefix sorts lexicographically)
    active.sort(key=lambda t: t[0].name, reverse=True)

    lines = [AUTO_HEADER]

    if active:
        for path, fm in active:
            lines.append(_fmt_inflight_entry(path, fm))
    else:
        lines.append("_(none)_")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API: lint_backlog
# ---------------------------------------------------------------------------

def lint_backlog(backlog_path: Path) -> list[str]:
    """Check ## title uniqueness in backlog, skipping HTML comment blocks.

    Returns list of error strings (empty = OK).
    """
    if not backlog_path.exists():
        return []

    text = backlog_path.read_text(encoding="utf-8")
    errors: list[str] = []
    seen: dict[str, int] = {}

    # Strip HTML comment blocks <!-- ... --> before parsing titles
    stripped = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)

    for line in stripped.splitlines():
        m = re.match(r"^##\s+(.+)", line)
        if m:
            title = m.group(1).strip()
            if title in seen:
                errors.append(f"duplicate backlog entry: '{title}'")
            else:
                seen[title] = 1

    return errors


# ---------------------------------------------------------------------------
# Public API: check_branch_active
# ---------------------------------------------------------------------------

def check_branch_active(branch: str, plans_root: Path | None = None) -> tuple[int, str]:
    """Return (exit_code, message). Exit 1 if branch has an active plan.

    The plans_root kwarg defaults to PLANS_ROOT but allows test override.
    """
    root = plans_root if plans_root is not None else PLANS_ROOT
    all_plans = _collect_plans(root)

    for path, fm in all_plans:
        if fm.get("branch") == branch and fm.get("status") == "active":
            summary = fm.get("summary", path.stem)
            msg = (
                f"Branch '{branch}' has an active plan: '{summary}'. "
                f"Run `board.py finish` or `board.py abandon` before merging."
            )
            return 1, msg

    return 0, f"No active plan found for branch '{branch}'."


# ---------------------------------------------------------------------------
# Internal: _find_backlog_entry / _remove_backlog_entry
# ---------------------------------------------------------------------------

def _find_backlog_entry(backlog_path: Path, title: str) -> tuple[int, int] | None:
    """Return (start, end) byte offsets of the matching ## title entry.

    An entry runs from its ## heading to just before the next ## heading (or EOF).
    HTML comment blocks are skipped during title matching.
    Returns None if not found.
    """
    text = backlog_path.read_text(encoding="utf-8")
    # Find all ## headings (not inside HTML comment blocks)
    # We'll work on lines to find heading positions
    lines = text.splitlines(keepends=True)
    pos = 0
    headings: list[tuple[str, int, int]] = []  # (title, byte_start, line_idx)

    in_comment = False
    for i, line in enumerate(lines):
        # Track HTML comment state
        if "<!--" in line:
            in_comment = True
        if "-->" in line:
            in_comment = False
            pos += len(line.encode("utf-8"))
            continue
        if not in_comment:
            m = re.match(r"^##\s+(.+)", line)
            if m:
                headings.append((m.group(1).strip(), pos, i))
        pos += len(line.encode("utf-8"))

    # Find the target heading
    for idx, (heading_title, byte_start, line_idx) in enumerate(headings):
        if heading_title == title:
            # Entry ends at the start of the next heading, or EOF
            if idx + 1 < len(headings):
                _, next_start, _ = headings[idx + 1]
                return byte_start, next_start
            else:
                return byte_start, len(text.encode("utf-8"))

    return None


def _remove_backlog_entry(backlog_path: Path, title: str) -> None:
    """Remove the named entry from backlog and normalize trailing newlines."""
    offsets = _find_backlog_entry(backlog_path, title)
    if offsets is None:
        raise ValueError(f"Backlog entry not found: '{title}'")

    raw = backlog_path.read_bytes()
    start, end = offsets
    new_raw = raw[:start] + raw[end:]
    # Normalize: collapse multiple trailing newlines to exactly two
    text = new_raw.decode("utf-8")
    text = re.sub(r"\n{3,}$", "\n\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    backlog_path.write_text(text, encoding="utf-8")


# ---------------------------------------------------------------------------
# CLI command implementations
# ---------------------------------------------------------------------------

def _cmd_regenerate() -> None:
    """Write in-flight.md from active plans."""
    BOARD_ROOT.mkdir(parents=True, exist_ok=True)
    content = build_in_flight(PLANS_ROOT)
    IN_FLIGHT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {IN_FLIGHT_PATH}")


def _regen_index() -> None:
    """Regenerate INDEX.md using docs_index.build_index()."""
    content = docs_index.build_index(DOCS_ROOT)
    INDEX_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {INDEX_PATH}")


def _cmd_lint_backlog() -> None:
    """CLI wrapper for lint_backlog."""
    errors = lint_backlog(BACKLOG_PATH)
    if errors:
        for e in errors:
            print(f"ERROR: {e}")
        sys.exit(1)
    else:
        print("OK — backlog has no duplicate entries")


def _cmd_check_merge(branch: str) -> None:
    """Check if branch can be merged. Exits 1 if there's an active plan."""
    rc, msg = check_branch_active(branch)
    print(msg)
    sys.exit(rc)


def _cmd_check_pr(branch: str) -> None:
    """Check gate for GitHub Actions PRs. Uses ::error:: prefix on failure."""
    rc, msg = check_branch_active(branch)
    if rc != 0:
        print(f"::error::{msg}")
    else:
        print(msg)
    sys.exit(rc)


def _flip_status_in_file(path: Path, new_status: str) -> None:
    """Regex replace status: X in frontmatter."""
    text = path.read_text(encoding="utf-8")
    new_text = re.sub(r"^status:.*$", f"status: {new_status}", text, count=1, flags=re.MULTILINE)
    path.write_text(new_text, encoding="utf-8")


def _find_active_plan_for_branch(branch: str) -> tuple[Path, dict[str, Any]] | None:
    """Find the one active plan for a branch. Returns (path, fm) or None."""
    all_plans = _collect_plans(PLANS_ROOT)
    for path, fm in all_plans:
        if fm.get("branch") == branch and fm.get("status") == "active":
            return path, fm
    return None


def _other_active_plans_reference_spec(plan_to_exclude: Path, spec_name: str) -> bool:
    """Check if any other active plan references the given spec."""
    all_plans = _collect_plans(PLANS_ROOT)
    for path, fm in all_plans:
        if path == plan_to_exclude:
            continue
        if fm.get("status") != "active":
            continue
        related = fm.get("related")
        if isinstance(related, dict) and related.get("spec") == spec_name:
            return True
    return False


def _finish_or_abandon(new_status: str) -> None:
    """Flip plan (and linked spec if full tier and not shared), regenerate, git add."""
    branch = _current_branch()
    result = _find_active_plan_for_branch(branch)
    if result is None:
        print(f"ERROR: No active plan found for branch '{branch}'.")
        sys.exit(1)

    plan_path, fm = result
    tier = fm.get("tier", "lite")
    touched: list[Path] = [plan_path]

    # Flip the plan status
    _flip_status_in_file(plan_path, new_status)
    print(f"Updated {plan_path.name}: status -> {new_status}")

    # For full tier, also flip the spec if not shared
    if tier == "full":
        related = fm.get("related")
        if isinstance(related, dict) and "spec" in related:
            spec_name = related["spec"]
            spec_path = SPECS_ROOT / spec_name
            if spec_path.exists():
                if not _other_active_plans_reference_spec(plan_path, spec_name):
                    _flip_status_in_file(spec_path, new_status)
                    print(f"Updated {spec_path.name}: status -> {new_status}")
                    touched.append(spec_path)
                else:
                    print(f"Skipping spec {spec_name} — referenced by another active plan.")

    # Regenerate board files
    BOARD_ROOT.mkdir(parents=True, exist_ok=True)
    content = build_in_flight(PLANS_ROOT)
    IN_FLIGHT_PATH.write_text(content, encoding="utf-8")
    touched.append(IN_FLIGHT_PATH)

    _regen_index()
    touched.append(INDEX_PATH)

    _git_add(touched)
    print(f"Done. Run `git commit` to finalize.")


def _cmd_finish() -> None:
    """Mark the active plan as done."""
    _finish_or_abandon("done")


def _cmd_abandon() -> None:
    """Mark the active plan as abandoned."""
    _finish_or_abandon("abandoned")


def _cmd_start(title: str, tier: str) -> None:
    """Move backlog entry to in-flight: scaffold plan stub (+ spec stub for full tier),
    remove from backlog, regenerate in-flight + index, git add touched files.
    """
    # Validate tier
    if tier not in ("lite", "full"):
        print(f"ERROR: Invalid tier '{tier}'. Must be 'lite' or 'full'.")
        sys.exit(1)

    # Check entry exists in backlog
    if not BACKLOG_PATH.exists():
        print(f"ERROR: Backlog not found at {BACKLOG_PATH}")
        sys.exit(1)

    offsets = _find_backlog_entry(BACKLOG_PATH, title)
    if offsets is None:
        print(f"ERROR: Backlog entry not found: '{title}'")
        sys.exit(1)

    branch = _current_branch()
    date = _today()
    slug = _slugify(title)
    touched: list[Path] = []

    # Scaffold spec stub (full tier only)
    spec_filename: str | None = None
    if tier == "full":
        spec_filename = f"{date}-{slug}-design.md"
        spec_path = SPECS_ROOT / spec_filename
        SPECS_ROOT.mkdir(parents=True, exist_ok=True)
        spec_content = _SPEC_STUB.format(date=date, title=title)
        spec_path.write_text(spec_content, encoding="utf-8")
        print(f"Created {spec_path}")
        touched.append(spec_path)

    # Scaffold plan stub
    plan_filename = f"{date}-{slug}.md"
    plan_path = PLANS_ROOT / plan_filename
    PLANS_ROOT.mkdir(parents=True, exist_ok=True)

    if tier == "full" and spec_filename:
        plan_content = _PLAN_STUB_FULL.format(
            date=date,
            title=title,
            branch=branch,
            spec_filename=spec_filename,
        )
    else:
        plan_content = _PLAN_STUB_LITE.format(date=date, title=title, branch=branch)

    plan_path.write_text(plan_content, encoding="utf-8")
    print(f"Created {plan_path}")
    touched.append(plan_path)

    # Remove from backlog
    _remove_backlog_entry(BACKLOG_PATH, title)
    print(f"Removed '{title}' from backlog.")
    touched.append(BACKLOG_PATH)

    # Regenerate in-flight.md
    BOARD_ROOT.mkdir(parents=True, exist_ok=True)
    in_flight_content = build_in_flight(PLANS_ROOT)
    IN_FLIGHT_PATH.write_text(in_flight_content, encoding="utf-8")
    touched.append(IN_FLIGHT_PATH)

    # Regenerate index
    _regen_index()
    touched.append(INDEX_PATH)

    # Git add all touched files
    _git_add(touched)
    print(f"Staged {len(touched)} file(s). Run `git commit` to finalize.")


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Board lifecycle automation")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("regenerate", help="Regenerate in-flight.md from active plans")
    sub.add_parser("lint-backlog", help="Check backlog for duplicate entries")

    start_p = sub.add_parser("start", help="Move a backlog entry to in-flight")
    start_p.add_argument("title", help="Exact title of the backlog entry")
    start_p.add_argument(
        "--tier",
        choices=["lite", "full"],
        default="lite",
        help="Plan tier: lite (plan only) or full (spec + plan)",
    )

    sub.add_parser("finish", help="Mark active plan as done")
    sub.add_parser("abandon", help="Mark active plan as abandoned")

    check_merge_p = sub.add_parser("check-merge", help="Gate for git merge")
    check_merge_p.add_argument("branch", help="Branch name to check")

    check_pr_p = sub.add_parser("check-pr", help="Gate for GitHub Actions PR check")
    check_pr_p.add_argument("branch", help="Branch name to check")

    args = parser.parse_args(argv)

    if args.command == "regenerate":
        _cmd_regenerate()
    elif args.command == "lint-backlog":
        _cmd_lint_backlog()
    elif args.command == "start":
        _cmd_start(args.title, args.tier)
    elif args.command == "finish":
        _cmd_finish()
    elif args.command == "abandon":
        _cmd_abandon()
    elif args.command == "check-merge":
        _cmd_check_merge(args.branch)
    elif args.command == "check-pr":
        _cmd_check_pr(args.branch)


if __name__ == "__main__":
    main()
