"""Frontmatter indexer for docs/superpowers/.

Usage:
    python docs_index.py regenerate          # write INDEX.md
    python docs_index.py lint [file ...]     # validate frontmatter
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from frontmatter import parse_frontmatter

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TRACKED_DIRS = ("specs", "plans", "reports", "handoffs")
REQUIRED_FIELDS = ("status", "type", "date", "summary")
VALID_STATUS = {"draft", "active", "done", "abandoned", "superseded"}
VALID_TYPE = {"spec", "plan", "report", "handoff"}
VALID_TIER = {"full", "lite"}

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_ROOT = REPO_ROOT / "docs" / "superpowers"
INDEX_PATH = DOCS_ROOT / "INDEX.md"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _collect(docs_root: Path) -> list[dict[str, Any]]:
    """Walk tracked dirs and return list of record dicts."""
    records: list[dict[str, Any]] = []
    for subdir in TRACKED_DIRS:
        d = docs_root / subdir
        if not d.is_dir():
            continue
        for p in sorted(d.glob("*.md")):
            fm = parse_frontmatter(p)
            rel = p.relative_to(docs_root)
            records.append({
                "path": rel.as_posix(),
                "name": p.name,
                "frontmatter": fm,
            })
    return records


def _fmt_entry(rec: dict[str, Any]) -> str:
    """Format one index line."""
    fm = rec["frontmatter"]
    name = rec["name"]
    path = rec["path"]

    if fm is None:
        return f"- [`{name}`]({path})"

    date = fm.get("date", "")
    doc_type = fm.get("type", "")
    summary = fm.get("summary", "")

    # Build related extras string
    extras: list[str] = []
    related = fm.get("related")
    if isinstance(related, dict):
        for k, v in related.items():
            extras.append(f"{k}: {v}")
    branch = fm.get("branch")
    if branch:
        extras.append(f"branch: {branch}")

    extras_str = " _(" + ", ".join(extras) + ")_" if extras else ""
    return f"- `{date}` `{doc_type}` [`{name}`]({path}) — {summary}{extras_str}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_index(docs_root: Path) -> str:
    """Build and return the full INDEX.md content string."""
    records = _collect(docs_root)

    active: list[dict] = []
    done: list[dict] = []
    legacy: list[dict] = []
    abandoned: list[dict] = []

    for rec in records:
        fm = rec["frontmatter"]
        if fm is None:
            legacy.append(rec)
        else:
            status = fm.get("status", "")
            if status in ("draft", "active"):
                active.append(rec)
            elif status == "done":
                done.append(rec)
            elif status in ("abandoned", "superseded"):
                abandoned.append(rec)
            else:
                # Unknown status — treat as active
                active.append(rec)

    # Limit recently done to 20
    done_limited = done[-20:] if len(done) > 20 else done

    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/docs_index.py — DO NOT EDIT -->",
        "",
        "# Superpowers docs index",
        "",
        "## Active",
        "",
    ]

    if active:
        for rec in active:
            lines.append(_fmt_entry(rec))
    else:
        lines.append("_(none)_")

    lines += [
        "",
        "## Recently done",
        "",
    ]

    if done_limited:
        for rec in done_limited:
            lines.append(_fmt_entry(rec))
    else:
        lines.append("_(none)_")

    lines += [
        "",
        "## Abandoned / superseded",
        "",
    ]

    if abandoned:
        for rec in abandoned:
            lines.append(_fmt_entry(rec))
    else:
        lines.append("_(none)_")

    lines += [
        "",
        "## Legacy (unfrontmattered)",
        "",
    ]

    if legacy:
        for rec in legacy:
            lines.append(_fmt_entry(rec))
    else:
        lines.append("_(none)_")

    lines.append("")
    return "\n".join(lines)


def lint(paths: list[Path]) -> tuple[list[str], list[str]]:
    """Validate frontmatter in the given files.

    Returns (errors, warnings).
    """
    errors: list[str] = []
    warnings: list[str] = []

    for p in paths:
        fm = parse_frontmatter(p)
        if fm is None:
            # No frontmatter — not an error for legacy files, skip
            continue

        name = p.name

        # Check required fields
        for field in REQUIRED_FIELDS:
            if field not in fm or fm[field] == "":
                errors.append(f"{name}: missing required field `{field}`")

        # Validate status enum
        status = fm.get("status", "")
        if status and status not in VALID_STATUS:
            errors.append(f"{name}: invalid status `{status}` (must be one of {sorted(VALID_STATUS)})")

        # Validate type enum
        doc_type = fm.get("type", "")
        if doc_type and doc_type not in VALID_TYPE:
            errors.append(f"{name}: invalid type `{doc_type}` (must be one of {sorted(VALID_TYPE)})")

        # Plans require branch and tier
        if doc_type == "plan":
            if "branch" not in fm or fm["branch"] == "":
                errors.append(f"{name}: plan missing required field `branch`")
            if "tier" not in fm or fm["tier"] == "":
                errors.append(f"{name}: plan missing required field `tier`")

        # Validate tier if present
        tier = fm.get("tier", "")
        if tier:
            if tier not in VALID_TIER:
                errors.append(f"{name}: invalid tier `{tier}` (must be one of {sorted(VALID_TIER)})")
            else:
                related = fm.get("related")
                has_spec = isinstance(related, dict) and "spec" in related

                if tier == "full" and not has_spec:
                    errors.append(f"{name}: tier `full` requires `related.spec`")
                elif tier == "lite" and has_spec:
                    errors.append(f"{name}: tier `lite` forbids `related.spec`")

        # Warn if done without related.pr
        if status == "done":
            related = fm.get("related")
            has_pr = isinstance(related, dict) and "pr" in related
            if not has_pr:
                warnings.append(f"{name}: status `done` without `related.pr`")

    return errors, warnings


# ---------------------------------------------------------------------------
# CLI commands
# ---------------------------------------------------------------------------

def _cmd_regenerate() -> None:
    """Write INDEX.md to DOCS_ROOT."""
    content = build_index(DOCS_ROOT)
    INDEX_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {INDEX_PATH}")


def _cmd_lint(file_args: list[str]) -> None:
    """Validate files from argv."""
    if file_args:
        paths = [Path(f) for f in file_args]
    else:
        # Lint all tracked files
        paths = []
        for subdir in TRACKED_DIRS:
            d = DOCS_ROOT / subdir
            if d.is_dir():
                paths.extend(sorted(d.glob("*.md")))

    errors, warnings = lint(paths)

    for w in warnings:
        print(f"WARNING: {w}")
    for e in errors:
        print(f"ERROR: {e}")

    if errors:
        sys.exit(1)
    else:
        print(f"OK — {len(paths)} file(s) checked, {len(warnings)} warning(s)")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Frontmatter indexer for docs/superpowers/"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("regenerate", help="Regenerate INDEX.md")

    lint_p = sub.add_parser("lint", help="Validate frontmatter")
    lint_p.add_argument("files", nargs="*", help="Files to lint (default: all tracked)")

    args = parser.parse_args(argv)

    if args.command == "regenerate":
        _cmd_regenerate()
    elif args.command == "lint":
        _cmd_lint(args.files)


if __name__ == "__main__":
    main()
